name: CI - Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências e executar o teste
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest tests/